[build]
  # Directorio base del proyecto (raíz del monorepo)
  base = "."
  
  # Comando para construir el frontend
  command = "cd frontend && npm ci && npm run build"
  
  # Directorio donde se generan los archivos estáticos
  publish = "frontend/dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "22.14.0"
  
  # Variables de entorno para el build
  NODE_ENV = "production"

# Configuración de redirects para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para archivos HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configuración de funciones (si necesitas serverless functions en el futuro)
[functions]
  directory = "netlify/functions"

# Configuración de plugins (opcional)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
